Replace hash of default-builder.sh to work around nix issues
In current versions of nix (but not 2.3!), "g0gn91m56b267ncx05w93kihyqia39cm"
appearing anywhere in the code makes fetching the source tarball fail, saying:

error: illegal path references in fixed-output derivation
    '/nix/store/i48lga5sk35ni87fwv17cijxlf0pcy0j-source.drv'

This is because it's interpreted as a reference to:
    /nix/store/g0gn91m56b267ncx05w93kihyqia39cm-builder.sh

We don't actually need the test to contain a valid, buildable derivation, just
one which parses correctly, so I've replaced the hash with all-f's.

Signed-off-by: embr <git@liclac.eu>